# SPDX-License-Identifier: GPL-2.0
#
# Makefile for nfc devices
#

ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/clkbuf/src/

obj-y	+= nxp533.o
