#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
#ifeq ($(TARGET_BUILD_VARIANT),eng)
#	obj-y += ov9281mipiraw_Sensor_eng.o
#else
#	obj-y += ov9281mipiraw_Sensor_userdebug.o
#endif

obj-y += ov9281mipiraw_Sensor.o

