#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/focaltech_touch_v3
obj-y += basic_util.o
obj-y += i2c_communication.o
obj-y += qual_core.o
obj-y += semi_touch_function.o
obj-y += semi_touch_upgrade.o
obj-y += semi_touch_apk.o
obj-y += semi_touch_device.o
obj-y += semi_touch_custom.o



